import type { Product } from './product';
export type CartItem = {
    product: Product;
    quantity: number;
    unit_price: number;
    total: number;
};
export type OrderItem = {
    id: number;
    user_id: number | null;
    name: string;
    sku: string;
    quantity: number;
    unit_price: string;
    total: string;
};
export type Order = {
    id: number;
    number: string;
    status: string;
    payment_status: string;
    receipt_type: 'boleta' | 'factura' | 'sales_note';
    receipt_status: 'pending' | 'issued' | 'sent' | 'rejected';
    receipt_series: string | null;
    receipt_number: string | null;
    receipt_url: string | null;
    payment_method: string;
    payment_reference?: string | null;
    payment_receipt_path?: string | null;
    shipping_method: string;
    customer_name: string;
    customer_email: string;
    customer_phone: string;
    address: string;
    district: string;
    province: string;
    department: string;
    subtotal: string;
    shipping_total: string;
    total: string;
    created_at: string;
    items: OrderItem[];
    electronic_documents?: { id: number; number: string; type: string; status: string; total: string; payload_json: Record<string, unknown>; response_json: Record<string, unknown> | null; xml_path: string | null; cdr_path: string | null }[];
    items_count?: number;
};
