export type SoftwareProgram = {
    id: number;
    name: string;
    slug: string;
    category: string;
    platform: string | null;
    version: string | null;
    license_type: string;
    price: string | null;
    short_description: string;
    description: string | null;
    requirements: string | null;
    installation_instructions: string | null;
    tutorial_url: string | null;
    download_enabled: boolean;
    can_download?: boolean;
    is_own: boolean;
    is_featured: boolean;
    is_active: boolean;
    downloads: number;
    image_url: string | null;
};
